### ISSUE TITLE
Update link?

### ISSUE THREAD

**Issue by danoff** [opinionlab/clojure-setup#4]
If/when there is time and interest, this link could use an updated http://eigenhombre.com/clojure/2012/05/21/resources-for-learning-clojure/ in the "Books and videos" section.

**Comment by Opus1no2** [comment]
I'll try and get to it when I can! Just kidding - not sure how I'm still on
this list.

**Comment by eigenhombre** [comment]
@Opus1no2 You are on it because you're following the repo. Cheers, JJ

**Comment by Opus1no2** [comment]
Ah ok - makes sense!

**Comment by eigenhombre** [comment]
@danoff I fixed the link and updated a few more things. Thanks!
